---
- name: Install pip (for github action)
  ansible.builtin.dnf:
    name: python3-pip
    state: latest

- name: Install githbub3.py (for github action)
  ansible.builtin.pip:
    name: github3.py
    state: latest

- name: Install Nitro
  ansible.builtin.dnf:
    name:  aws-nitro-enclaves-cli
    state: latest

- name: Enable services (docker, nitro alocator)
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - docker
    - nitro-enclaves-allocator

- name: Prepare directory
  ansible.builtin.file:
    path: "/usr/local/{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  loop:
    - glove
    - glove/log

- name: Get latest release of glove
  community.general.github_release:
    user: projectglove
    repo: glove-monorepo
    action: latest_release
  register: glove_release

- ansible.builtin.debug:
    msg: "{{ glove_release.tag}} is the tag"

- name: Download Glove artifacts
  ansible.builtin.get_url:
    url: https://github.com/projectglove/glove-monorepo/releases/download/{{glove_release.tag }}/{{ item }}
    dest: /usr/local/glove
    owner: root
    group: root
    mode: 0755
  loop:
     - service
     - glove.eif
  notify:
     - Restart daemon

- name: Copy Glove Service file
  ansible.builtin.template:
    src: glove.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart daemon

- name: Set Glove service
  ansible.builtin.systemd_service:
    name: glove
    state: started
    enabled: true
