[package]
name = "common"
description = "Common types and utilities used by all three components: service, client, and enclave."
version = "0.1.0"
edition = "2021"

[dependencies]
parity-scale-codec.workspace = true
rand.workspace = true
sp-core.workspace = true
aws-nitro-enclaves-cose.workspace = true
aws-nitro-enclaves-nsm-api.workspace = true
serde_cbor.workspace = true
openssl.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
