name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

# To double check
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: ./build.sh

      - name: Service and enclave artifacts
        uses: actions/upload-artifact@v4
        with:
          name: glove-service
          path: |
            target/release/service
            target/release/glove.eif

      - name: Enclave measurement artifact
        uses: actions/upload-artifact@v4
        with:
          name: enclave_measurement
          path: target/release/enclave_measurement.txt

      - name: Adding measurement to summary
        run: |
          echo '### Enclave Image Measurement' >> $GITHUB_STEP_SUMMARY
          cat target/release/enclave_measurement.txt >> $GITHUB_STEP_SUMMARY

      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/service
            target/release/glove.eif
          make_latest: true

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible

      - name: Install boto
        run: |
           pipx inject ansible-core boto3
           pipx inject ansible-core botocore

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com.
          role-to-assume: arn:aws:iam::381491931967:role/GitHubAction-EC2-RO
          role-session-name: deploy-role-session
          aws-region: us-east-2



      - name: Run Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: glove.yml
          directory: devops/ansible
          configuration: |
            [defaults]
            inventory = inventory_aws_ec2.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory inventory_aws_ec2.yml
