name: Release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: ./build.sh

      - name: Service and enclave artifacts
        uses: actions/upload-artifact@v4
        with:
          name: glove-service
          path: |
            target/release/service
            target/release/glove.eif

      - name: Enclave measurement artifact
        uses: actions/upload-artifact@v4
        with:
          name: enclave_measurement
          path: target/release/enclave_measurement.txt

      - name: Adding measurement to summary
        run: |
          echo '### Enclave Image Measurement' >> $GITHUB_STEP_SUMMARY
          cat target/release/enclave_measurement.txt >> $GITHUB_STEP_SUMMARY

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Make release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/release/service, target/release/glove.eif
          makeLatest: true
          prerelease: true # For now
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
