---
name: Test

on:
  push:
    branch:
      - "one-more-fix"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - shell: bash
        env:
          SECRET: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SECRET" > key
          chmod 600 key
          ls -l
          ssh-keygen -y -f key
          dig +short myip.opendns.com @resolver1.opendns.com
          ssh -o "StrictHostKeyChecking=no" -i key -vvv ec2-user@52.14.26.216 ls
