---
name: Test

on:
  push:
    branch:
      - "devops/fix*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible

      - name: Install boto
        run: |
          sudo pip3 install boto3 botocore

      - name: Run Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: glove.yml
          directory: devops/ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts.ini
